post_install() {
    systemctl enable --now repo-synchroniser.timer || true
}

post_upgrade() {
    systemctl --system daemon-reload >/dev/null || true
    systemctl restart repo-synchroniser.timer || true
}

pre_remove() {
    if [ -d /run/systemd/system ]; then
        systemctl disable --now repo-synchroniser.timer >/dev/null
    fi
}

post_remove() {
    if [ -d /run/systemd/system ] ; then
        systemctl --system daemon-reload >/dev/null || true
    fi
}

